### ISSUE TITLE
Visual problems in the firefox dev edition dark theme

### ISSUE THREAD

**Issue by svinqvmraka** [seleznev/firefox-extension-htitle#54]
As you probably have seen, as of yesterday, there is a firefox developer edition that uses a dark theme by default.

There is a white line above the tab bar and the window controls' background is also white. 

![screenshot from 2014-11-11 14 22 53](https://cloud.githubusercontent.com/assets/3404749/4992785/6a3664f2-69ae-11e4-8506-13c3f2aedfeb.png)

Not a huge problem, but it's still annoying.

**Comment by svinqvmraka** [comment]
Hey, I just noticed this is still open, just letting you know that the above problems are resolved for me. FF v37, gnome 3.14 on archlinux.
![hopuzrs](https://cloud.githubusercontent.com/assets/3404749/5864803/7fddd020-a28d-11e4-849a-a5c22ac0e0db.png)

**Comment by seleznev** [comment]
Well, it's very nice. I close this issue in this case.

Many thanks. :)
