### ISSUE TITLE
No control buttons after hiding window bar

### ISSUE THREAD

**Issue by jgato** [seleznev/firefox-extension-htitle#56]
Hi there,

I have been using this theme together with htittle and gnome theme tweak to make Firefox look more like gnome-shell.

With the new update to Firefox 35 I cannot see the control buttons (close, minimize, maximize) after hiding window bar. This does not happen with the default theme. What could I do? I dont know if it is an issue with this extension or with the Firefox-Gnome theme (I have also created an issue there https://github.com/gnome-integration-team/firefox-gnome/issues/314)

More details: Ubuntu 14.04 and Gnome-Shell 3.10

thanks and regards,

**Comment by seleznev** [comment]
> This does not happen with the default theme.

=> closed. :)
