### ISSUE TITLE
XChangeProperty

### ISSUE THREAD

**Issue by Noitidart** [seleznev/firefox-extension-htitle#59]
Hi there I saw you have some x11 js-ctypes going. I was looking to use XChangeProperty to change the icon of the window, taskbar, and alt+tab menu. I was wondering if you had done that before? I'm going to start now working on it. Just wondering if you tried it or if you can help spoon feed :P Thanks and awesome ctypes work btw!

**Comment by seleznev** [comment]
> icon of the window, taskbar, and alt+tab menu

In GNOME Shell you can use .desktop files to do this.

---

In any case, you should look on [FireTray](https://github.com/foudfou/FireTray) extension. Maybe it can help you.

**Comment by Noitidart** [comment]
Thanks very much @seleznev  I created the jsctypes: https://gist.github.com/Noitidart/325c81e8df5b3efb85f8#file-xchangeproperty-_net_wm_icon-L382

:(

I hard coded the data of the image in there so you can copy paste and run that in scratchpad and it will attempt to change the icon of the most recent navigator:browser type window. Can you please take a look if you get a chance :)

**Comment by Noitidart** [comment]
Man I thought I had to do XWMHints update to make the icon show, but it just won't show :(

Here's the XWMHints code, also copy pastable: https://gist.github.com/Noitidart/f426bae5b0d7782c98bd

**Comment by seleznev** [comment]
@Noitidart, I'm so sorry, but I can't help you with it. :(

**Comment by Noitidart** [comment]
Aw darn ok thanks for the read though :)
