### ISSUE TITLE
When trying to resize, menu pop ups instead

### ISSUE THREAD

**Issue by freed00m** [seleznev/firefox-extension-htitle#60]
I am no using Gnome3, I am on MATE 1.8
When trying to resize window with mouse, a mouseleft click spawns a clasic menu like if I right clicked.

My appologies if you wont care for non gnome3 systems. :) keep up the good work. Cheers
---
v3.3
Hide is on always
No legacy
No only work with Gnomeshell.

**Comment by chpii** [comment]
Is there still a problem? Can you attach a screenshot of how your Firefox looks?

**Comment by freed00m** [comment]
http://youtu.be/0vAQh2fa_as right or left click behave the same, Mint MATE

**Comment by chpii** [comment]
What is your WM(Metacity) theme name?

I think this is relevant to https://github.com/seleznev/firefox-extension-htitle/issues/29

The problem may be that border is only 1px, not only that is hard to drag normally. Try adjusting it to something more as said in second comment.

**Comment by seleznev** [comment]
@freed00m,

1. Open a terminal window.
2. Type following command: `xprop -f _MOTIF_WM_HINTS 32c -set _MOTIF_WM_HINTS "0x2, 0x0, 0x2, 0x0, 0x0"`
3. Click on any window (a terminal window, for example). Window decorations will be hide.
4. Is bug exists with this window?

**Comment by freed00m** [comment]
@seleznev 

Well it must be my metacity then 
>> xprop -f _MOTIF_WM_HINTS 32c -set _MOTIF_WM_HINTS "0x2, 0x0, 0x2, 0x0, 0x0"
applyed on any other window will reintroduce this dragging issue :( 

Then I appologize for bothering, but I have no idea how to fix my metacity wm: Marco

**Comment by chpii** [comment]
You can open issue here: https://github.com/mate-desktop/marco/issues

This is entirely bug in Marco

**Comment by freed00m** [comment]
Thanx I will do so :)
