### ISSUE TITLE
Close button stopped working in Firefox 38

### ISSUE THREAD

**Issue by kparal** [seleznev/firefox-extension-htitle#63]
In Firefox 38, when using HTitle 3.4 and having the window maximized, the window close button does nothing on press. I can still close Firefox by using Alt+F4 or by unmaximizing and pressing the native close button.

**Comment by seleznev** [comment]
I can't reproduce it. Can you try to disable/remove HTitle, open Firefox in fullscreen and then click on close button? Does it work?

**Comment by kparal** [comment]
Great idea. I've found out that it is not caused by htitle but by tab mix plus. Thanks, and sorry for confusion.

**Comment by IamLosted** [comment]
@kparal Have you managed to configure tab mix plus to overcome this issue?

**Comment by kparal** [comment]
@IamLosted No, I reported bug and I'm waiting: https://bitbucket.org/onemen/tabmixplus/issue/18/fullscreen-close-button-doesnt-work-on
