### ISSUE TITLE
Tabs drag & drop doesn't work anymore with GTK3 Firefox

### ISSUE THREAD

**Issue by marco-c** [seleznev/firefox-extension-htitle#69]

**Comment by seleznev** [comment]
HTitle doesn't support Firefox on GTK3. Sorry...

**Comment by marco-c** [comment]
Ok, GTK3 is now the default on Nightly, so basically the extension will be abandoned? Or do you plan to support it in the future?

**Comment by seleznev** [comment]
> Or do you plan to support it in the future?

Yes, when it will be in Beta.

---

I'm actually use Nightly right now, and I don't have any problems with tabs. So, It can be very hard to find solution.

**Comment by marco-c** [comment]
I've re-enabled the extension and drag & drop seems to work now!
