### ISSUE TITLE
Thunderbird close/minimize button in non-default style

### ISSUE THREAD

**Issue by art1fa** [seleznev/firefox-extension-htitle#70]
See screenshot below. On Firefox, however, the default GNOME buttons are shown.

Using GNOME 3.16 on Fedora 22, Thunderbird 38.1 and htitle 3.4.

![screenshot](https://cloud.githubusercontent.com/assets/11131859/9111984/fd1baaa0-3c4b-11e5-9590-ba833109aa12.png)

Expected result (like in Firefox):

![screenshot from 2015-08-06 15-03-40](https://cloud.githubusercontent.com/assets/11131859/9112041/6731386a-3c4c-11e5-9a0d-23875f4f6718.png)

**Comment by seleznev** [comment]
This behavior is correct. You should use theme to change window controls buttons (you use GNOME Theme for that in Firefox, for ex.).
