### ISSUE TITLE
Not full Integration with theme color

### ISSUE THREAD

**Issue by vantu5z** [seleznev/firefox-extension-htitle#71]
Seems that it use only one color, but not gradient:
![2015-08-11 08-47-50](https://cloud.githubusercontent.com/assets/8698003/9191118/f377412c-4005-11e5-8d11-cf37592e9ef7.png)

**Comment by seleznev** [comment]
HTitle doesn't change theme colors. Can you disable HTitle, open window in fullscreen mode and make a same screenshot?

**Comment by vantu5z** [comment]
Without HTitle looks like this:
![2015-08-11 19-43-23](https://cloud.githubusercontent.com/assets/8698003/9203775/c8f9e01a-4061-11e5-8663-f7c413443f3e.png)

**Comment by seleznev** [comment]
No, I mean "fullscreen" (`View` > `Fullscreen` or just press `F11`), not "maximized".

**Comment by vantu5z** [comment]
Sorry.
![2015-08-11 20-00-50](https://cloud.githubusercontent.com/assets/8698003/9204120/edb7e53a-4063-11e5-8c60-62c4f343f8f0.png)

**Comment by seleznev** [comment]
Well, looks like it isn't HTitle issue, because your theme do it too.

**Comment by vantu5z** [comment]
Ok, thanks. I try to ask theme developer.

**Comment by vantu5z** [comment]
Yes, it was the problem of theme, now it fixed.
